In [20]:
## Using Numpy
import numpy as np

In [5]:
n = np.arange(27)

In [7]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

# Work with images

In [2]:
import cv2

In [5]:
## read in an image with cv2
im_g = cv2.imread("Data/smallgray.png", 0) # read as greyscale so use 0
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [6]:
# Write and image with cv2
cv2.imwrite("Data/grey_img.png", im_g)

True

### Indexing, slicing and iterating

In [7]:
# create a list:
a = [1,2,3]

In [9]:
#slice
a[0:2]

[1, 2]

In [11]:
## with numpy
# for first two rows
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [12]:
# first two rows and thrid and fourth number
im_g[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [14]:
# check shape of a numpy array
im_g.shape

(3, 5)

In [17]:
## iterating from a numpy array:
for i in im_g:
        print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


### Stacking and splitting numpy arrays

In [21]:
# stack numpy arrays horizontally
im_s = np.hstack((im_g, im_g)) # note that we use a double bracker to indicate we are passing ina  'tupple'
im_s

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
#can also stack vertically
im_v = np.vstack((im_g, im_g))
im_v

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [24]:
## we can also split an array
lst = np.hsplit(im_s, 2)
lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]